services:
  - type: web
    name: bawdicsoft-agent
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MODEL_DIR
        value: ./model_out
      - key: PYTHON_VERSION
        value: 3.11.9